# Generated by Django 3.2.23 on 2024-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_crushesdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'This email is already in use.'}, max_length=254, unique=True, verbose_name='Email Address')),
                ('attempts', models.IntegerField(default=0)),
                ('first_attempt_time', models.DateTimeField(blank=True, null=True)),
                ('latest_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
